### ISSUE TITLE
Using slang with Kemal error

### ISSUE THREAD

**Issue by jwoertink** [jeromegn/slang#14]
I'm using slang with Kemal, but running in to a weird issue of slang swallowing `__FILE__` before kemal gets to it.

```crystal
# layout.slang
== yield_content("some_key")

# page.slang
- content_for("some_key") do
  h1 This does not get rendered
```

In Kemal, the [yield_content macro](https://github.com/kemalcr/kemal/blob/6b034c3b2f9e54ebbdedd929a5f4c841952a7a04/src/kemal/helpers/macros.cr#L50) takes the value of `__FILE__` and adds that as the first element in this Tuple. Then it compares that value to the current file calling it. With ECR, the value here would be `{"some_key" => {"views/page.ecr", #<Proc(String)...>}`, but in slang the value here is `{"some_key" => {"expanded macro: macro_1234332", #<Proc(String)...>}`. 

The current fix for this is to use this helper variable that's set in Kemal as the second argument to the `content_for` macro. Maybe you have an idea about this though?

**Comment by jeromegn** [comment]
Hmmm, that's weird. What version of Crystal are you running?

I have not been playing with Crystal as much lately. Maybe Slang needs to be updated. Or maybe it's Kilt that needs updating... 🤔

**Comment by jwoertink** [comment]
I'm using 0.20.1 with latest Kemal. I was actually working on this with @sdogruyol to confirm I wasn't doing something weird. We looked at Kilt to see if it could be that, but I'm still not sure where the best place to fix the issue would be.

**Comment by sdogruyol** [comment]
Maybe we should ping @asterite for better explanation about `__FILE__` expansion in macros and why `ecr` does this correctly.

**Comment by asterite** [comment]
I'll need some code to reproduce this, because I'm not sure I understand what's the problem.

**Comment by sdogruyol** [comment]
@asterite uploading a minimal reproducible project asap

**Comment by sdogruyol** [comment]
@asterite please see https://github.com/sdogruyol/kemal-macro-file-problem

**Comment by asterite** [comment]
I'll soon fix the problem with `__FILE__`, but I don't know if it has anything to do with that...

Is Slang using location pragmas? It's a non-documented feature of the compiler (lexer) where you can override the current lexer's location. For example:

```cr
1 + #<loc:"foo.cr",12,34>2
```

This will make it so that the token `2` is considered to be at file "foo.cr", line 12, column 34. In that way errors in an ECR template can be shown in that file. I suggest you copy that behaviour from ECR.

**Comment by asterite** [comment]
I'll soon push a fix to the location not being fowarded by macros, for __FILE__, and then you'll be able to debug it with that. Maybe with that you can explain me how __FILE__ is the problem :-)

**Comment by jwoertink** [comment]
I'm not totally sold on it being a `__FILE__` issue... I think if we figure out why ECR returns "views/page.ecr", but slang returns "expanded macro: macro_1234332" then that could fix the problem. Now if it's `__FILE__` that is returning `expanded macro: macro_1234332`, then I guess it would be the issue.

**Comment by asterite** [comment]
@jwoertink Then the problem is missing location pragmas. [Check ECR specs](https://github.com/crystal-lang/crystal/blob/master/spec/std/ecr/ecr_spec.cr#L15-L31). You must do something similar in slang.

**Comment by elorest** [comment]
Has this been solved?

**Comment by jwoertink** [comment]
Nope. I'm still seeing this as an issue.

**Comment by jeromegn** [comment]
Ok, I've fixed a few things with release v1.7.0, but I haven't implemented pragmas yet.

I think part of the issue here was about macro scoping in an earlier version of Crystal. Can somebody confirm this?

**Comment by drum445** [comment]
Was this ever fixed, still not seeing rendered content via `content_for` and `yield_content`

**Comment by toddsundsted** [comment]
i did the minimum pragma hacking to get this to work in my fork: https://github.com/toddsundsted/slang

i also added support for multi-line blocks of text, embedded crystal blocks of code...

**Comment by jeromegn** [comment]
@toddsundsted happy to merge that if you PR :)

**Comment by toddsundsted** [comment]
@jeromegn i'll run the code in production for a couple days to make sure it's solid and i'll generate a patch
